### ISSUE TITLE
Procedures allow access to non-local variables

### ISSUE THREAD

**Issue by alexandra-hanson** [melt-umn/Oberon0#6]
I believe the example /examples/negative/name_errors/L3/8_non_local_var_proc.ob should produce errors since a nested procedure attempts to access a variable declared outside of its scope, but fails to do so. This is:

```
MODULE NonLocalVarProc;

PROCEDURE FOO;
  VAR x: INTEGER;

  PROCEDURE BAR;
    BEGIN
      x := 42;
    END BAR;
  
  END FOO;

END NonLocalVarProc.
```

It should not be able to access variable x within the scope of procedure BAR.

**Comment by ericvanwyk** [comment]
This is proper behavior - all that is happening is that variables declared in scopes enclosing BAR are visible in BAR. It is the same principle as accessing a global variable in a local scope, but extended to more fine-grained nested scoping.

**Comment by alexandra-hanson** [comment]
Yes, that makes sense. I thought that behavior made sense but I found the example in the negatives in https://github.com/ericvanwyk/ldta-2011 and saw that it produced no errors when run so I was unsure. Maybe a better negative test would be something like:

```
MODULE NonLocalVarProc;

PROCEDURE FOO;
  
  PROCEDURE BAR;
    VAR x: INTEGER;
    BEGIN
    END BAR;
  BEGIN
    x := 42;
  END FOO;

END NonLocalVarProc.
```

And the original example could be moved into the positive tests?

**Comment by ericvanwyk** [comment]
Good idea - do  this.
